# Generated by Django 5.1.6 on 2025-02-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
